### ISSUE TITLE
Define a way to ignore which uris should not be have authorization header

### ISSUE THREAD

**Issue by diegodfsd** [ideaq/hapi-auth-jwt2#22]
I'm using hapi-swagger and after that I added the jwt2 to my project I started taking a error when I access the documentation. The error generated because in this url there is not a authorization header and should not have it even. I think that should a way to inform which urls should have this header or there might be a pre-authenticate method where we can do what we want before authenticate.

Here we can see the code that is generating the error.

```
      var auth = request.headers.authorization;
      if (!auth) {
        return reply(Boom.unauthorized(null, 'Token not present'));
      }
```

**Comment by nelsonic** [comment]
@diegodfsd this is because the swagger urls are not being registered as `auth:false`.
see: http://hapijs.com/tutorials/auth#mode

**Comment by diegodfsd** [comment]
@nelsonic You are totally right I updated hapi-swagger and everything did work. I don't checked hapi-swagger's documentation to know if was possible it by pass the arguments to hapi.

Thanks

**Comment by nelsonic** [comment]
@diegodfsd sweet. glad it worked for you. Please star the repo to help us get more visibility. Abraço!
