### ISSUE TITLE
Update Dependencies to Latest jsonwebtoken?

### ISSUE THREAD

**Issue by nelsonic** [ideaq/hapi-auth-jwt2#23]
Deps out of date. 
![jwt-security-vulnerability](https://cloud.githubusercontent.com/assets/194400/7061029/99fad0ca-de83-11e4-9352-01a97f96e259.png)

**Comment by eventhough** [comment]
Looks good to me!

**Comment by nelsonic** [comment]
@eventhough I've already pushed the fix to NPM. if you are using the module, I recommend updating to: [**4.0.2**](https://www.npmjs.com/package/hapi-auth-jwt2)

**Comment by nelsonic** [comment]
PR: https://github.com/ideaq/hapi-auth-jwt2/pull/24  was *Merged* by @iteles
