### ISSUE TITLE
Can't pass jsonwebtoken.verify options

### ISSUE THREAD

**Issue by Think7** [ideaq/hapi-auth-jwt2#29]
Currently, users of this package cannot pass in verify options for the jsonwebtokens module as shown here:
https://www.npmjs.com/package/jsonwebtoken#jwt-verify-token-secretorpublickey-options-callback

I have resolved this issue but am unfamiliar with source control and how to make a pull request.
The modified index.js for can be found here: http://pastebin.com/kibMGb11

Users now need only to pass in a verifyOptions object in the options object for the module.
Example:

```javascript
    server.auth.strategy('jwt', 'jwt', true,
        {
            key: secret,
            validateFunc: validate,
            verifyOptions: {
                ignoreExpiration: true
            }
        }
    );
```
I also exported the JWT.sign method so now users of the package do not need to have specific requires for it in their project.

**Comment by nelsonic** [comment]
@Think7 Do you have control over *creating* the JWT? you could simple not set the expiration in the first place if you're just going to ignore it...

**Comment by Think7** [comment]
Agreed however i ran into an issue:

If client makes a request for a JWT with an expiry time of 10 mins, after the expiry time, server is going to 401 them. I need to allow users to send a potentially expired token and then check to see if they are allowed to renew their session (send them another JWT) without sending credentials over the wire a second+ time.

**Comment by nelsonic** [comment]
Ok. I don't have time to add it today. If you have time to add the code+tests and submit a pull request, please do. otherwise I will try and get to this tomorrow. :+1:

**Comment by nelsonic** [comment]
Implementation note: https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback

**Comment by Think7** [comment]
Each option is a bool which tells jwt to ignore the thing is it's mismatching.

For example you can have it ignore tokens where the issuer is different. Forgot where i read this.

**Comment by nelsonic** [comment]
@Think7 done. Grab the latest version from NPM and use how you you would expect (in the code you wrote above). thanks for letting us know you needed it! :+1:

**Comment by Think7** [comment]
Thanks you for adding it!

It looks like you removed my forwarding of the JTW's .sign() method. Was this intentional?

Also when you have time, pretend that you are a new user coming to this package. Follow the instructions on the main page, you'll see that you get compilation errors if you follow things exactly as shown.

**Comment by nelsonic** [comment]
:anguished: Please create that last message as a new issue and I will get on it *immediately*. 
Thanks again for the feedback!

**Comment by nelsonic** [comment]
@Think7 we have ***updated*** the **readme** and ***simplified*** the **example** usage code. please review and confirm its more beginner-friendly. if you spot anything *please* create an issue so we can make it the *best* it *can* be! thanks again for your feedback/input! :+1:
