### ISSUE TITLE
Validate function omits callbacks error object.

### ISSUE THREAD

**Issue by Think7** [ideaq/hapi-auth-jwt2#35]
During implementation if the validate function for my app, i notice that if i pass an error object back, regardless of what that error object is, it is not passed correctly to the Hapi auth handler callback.

```javascript
var validate = function (decoded, request, callback) {
//    return callback("not nothing", false);
//    return callback({error: "Something TERRIBLE happened"}, true);
};
```
in the above case, the  first argument !null and should therefore be sent back to the handler for it to send it to the client.

See here: http://hapijs.com/tutorials/auth

The problem is here:
http://puu.sh/hgxHO/feae74cce8.png
As you can see the Boom.unauthorized is being sent regardless if we've supplied our own error object.

Possible (NOT PERFECT) fix:
http://puu.sh/hgyh7/8a5648275f.png

**Comment by nelsonic** [comment]
Hi @Think7 thanks for letting us know this was causing you grief.
The docs say we should use **Boom** to construct errors returned in the `reply`: http://hapijs.com/tutorials/auth#authenticate and we were keeping the message standard for simplicity.
But if you prefer to have the *specific* message that was returned from your `validateFunc`, would this be a good middle ground:
```js
if (err) {
  return reply(err, null, { credentials: credentials });
}
```

**Comment by Think7** [comment]
Looks good!

**Comment by nelsonic** [comment]
Done. see **4.3.0** on NPM: https://www.npmjs.com/package/hapi-auth-jwt2
@Think7 thanks again for drawing our attention to this.
Please star this repo and follow to show our fellow Hapi people this module is loved. thanks!
