### ISSUE TITLE
Avoid hitting database at every call to the auth strategy

### ISSUE THREAD

**Issue by mazzy89** [ideaq/hapi-auth-jwt2#41]
Which could be a good way to avoid hitting the database at every validation call? In the real example you  @nelsonic validate the token against elasticsearch every time. it would be great to cache it. I have thought to use a cache level like Memcached or Redis. What do you think about?

**Comment by nelsonic** [comment]
Hi @mazzy89 we aren't ignoring you. 
We already have an example using Redis: https://github.com/ideaq/hapi-auth-jwt2/blob/master/example/real_world_example_using_redis_on_heroku.js
Thanks *confirming* that its not very easy to find...! :wink:

**Comment by mazzy89** [comment]
Hi Nelson,
I have already thought to use Redis as a cache layer. I'm asking you if there are other ways to avoid hitting the database for validate the token. What about caching the token at the server side?

Salvatore Mazzarino

**Comment by nelsonic** [comment]
ah...! sorry I did not understand the first time.
Yes, you ***can*** **cache** the tokens on the node layer/server, however this would defeat the "stateless" objective of the server/cluster (making an extra step to scale horizontally).

**Comment by nelsonic** [comment]
Let us know what you decide to do for caching! :+1:

**Comment by mazzy89** [comment]
Actually I was thinking to use cookie to store token but how could this fit in the case of API consumed by mobile devices?

**Comment by nelsonic** [comment]
Good question. APIs accessed by Native apps can still send headers. 
But it would be a cross-domain cookie...
http://www.ibuildings.com/blog/2013/03/secure-your-rest-api-oauth2-implicit-grant
The token approach is easier.
