### ISSUE TITLE
Make the word "Bearer" in the Authorization header Optional.

### ISSUE THREAD

**Issue by nelsonic** [ideaq/hapi-auth-jwt2#6]
We are ***NOT*** implementing **OAuth 2.0** so I don't see the *point* of using the word "**Bearer**" in the ***Authorization*** header. see: https://tools.ietf.org/html/rfc6750#section-2.1
**Bearer** is a *useless* word that is just one more thing to  have to strip out of the header value and one more thing for developers to *forget* to add when sending a token!

**Comment by nelsonic** [comment]
As much as it ***pains*** me to include a *pointless* (*non-functional*) word in *EVERY* http (auth) header (request/response!!) I **propose** a ***compromise***: lets ***accept*** the word **Bearer** but strip it. So people have the *option* of using it if they want to.

**Comment by nelsonic** [comment]
100% optional.
see: https://github.com/ideaq/hapi-auth-jwt2/blob/4bc52c1432e0a83bab3c3a66a2c2ecb55dbbd4e3/lib/index.js#L38
and: https://github.com/ideaq/hapi-auth-jwt2/blob/4bc52c1432e0a83bab3c3a66a2c2ecb55dbbd4e3/test/test.js#L67

**Comment by pablocarreraest** [comment]
what is the difference between auth of jwt and oauth 2.0? I get confuse on that please can you explain me?
🍻 
thanks!

**Comment by nelsonic** [comment]
@pablocarreraest this should really be a question in a ***new issue*** so people can give you a good answer. 👍

**Comment by jmm** [comment]
@nelsonic Is an `Authorization` header without a scheme token valid HTTP? It doesn't seem so from my reading of the specs.

It seems questionable to me to treat these different values as identical, and is it not possible for a JWT to have an embedded substring that matches `/Bearer/i` that will be blown away by [this](https://github.com/dwyl/hapi-auth-jwt2/blob/d570a28966832e22f4704c7f034162e5d2a216ff/lib/extract.js#L30)? Further, if I'm reading that code right, the replacement will even be performed on values that didn't come in via an `Authorziation` header and to `Authorization` header values that already had a `tokenType` value (including `Bearer`) stripped.
