### ISSUE TITLE
Create "real-world" (Tested!) example using Redis?

### ISSUE THREAD

**Issue by nelsonic** [ideaq/hapi-auth-jwt2#9]
Should we have a more elaborate ("*real-world*") example people can use in their apps?

**Comment by manonthemat** [comment]
It would definitively be a nice extra.

**Comment by nelsonic** [comment]
This is *happening* today! #GetExcited! :wink: 
![get excited and make things](http://i.imgur.com/JV5F3Pg.jpg)

**Comment by nelsonic** [comment]
Pick up on: https://dashboard.heroku.com/apps/jwt2/settings

**Comment by nelsonic** [comment]
@manonthemat please see: **example/real_world_example_using_redis_on_heroku.js** (this repo)
